global using AutoMapper;
global using Humanizer;
global using MediaBox.Core.Interfaces;
global using MediaBox.Core.Models;
global using MediaBox.Core.Models.Api;
global using MediaBox.Core.Models.Enums;
global using MediaBox.Core.ViewModels.Languages;
global using MediaBox.Core.ViewModels.Media;
global using MediaBox.Core.ViewModels.Sources;
global using MediaBox.Frm.Models;
global using Newtonsoft.Json;
global using Octokit;
global using Refit;
global using Serilog;
global using Serilog.Core;
global using System.ComponentModel;
global using Credentials = MediaBox.Core.Models.Api.Credentials;
global using Language = MediaBox.Core.Models.Api.Language;
global using ProductHeaderValue = Octokit.ProductHeaderValue;